### ISSUE TITLE
Visual speech recognition

### ISSUE THREAD

**Issue by vstergiou** [AdityaYadavalli1/Kaldi-Recipe#1]
Hi, 
I want to use a GMM-HMM Kaldi recipe for visual speech recognition (fingerspelling recognition). Kaldi doesn't provide visual features, so I have already extracted my features with a VGG based model and then PCA (VGG dim is too high for GMM). Now I know that I need to convert these features from NumPy to ark format to fit Kaldi.

What changes do I need to make to train this recipe on my features? For example,  how can I skip feature extraction in run.sh script? 

Thank you in advance.

**Comment by AdityaYadavalli1** [comment]
Did you already convert NumPy features to ark format?

**Comment by vstergiou** [comment]
Not yet. But I'm planning to use kaldiio

**Comment by AdityaYadavalli1** [comment]
Okay I have only done the opposite, i.e. use kaldiio to convert ark files to numpy, so I will not be able to help you with that right away. But in this recipe you can skip "preparing acoustic data" and "features extraction" stages. I also would caution you to get the right dimensions (or similar to MFCC features) because I think the internal scripts (C++/python scripts) assume a particular number or you will have to change those internal files manually.

**Comment by vstergiou** [comment]
So, to skip "preparing acoustic data" and "features extraction" stages I just need to comment the corresponding lines at run.sh file, right? 

Also, what is the structure of the directories that feature files are typically stored ?

**Comment by AdityaYadavalli1** [comment]
Yes, you can comment those stages. 

There is no directory structure. All the scp/ark files are stored in `mfcc` folder which is at the same level as `run.sh`. Depending on the number of jobs you provide, it will divide and create those many scp/ark files.

**Comment by vstergiou** [comment]
So, the folder with ark files needs to be name "mfcc" in my case too ?

**Comment by AdityaYadavalli1** [comment]
Yes for this recipe. You can search for "mfccdir" in `run.sh` and change if you want to name it something else.

**Comment by AdityaYadavalli1** [comment]
I am closing this for now. Feel free to re-open it if you have anymore questions.
